name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Paramiko
        run: pip install paramiko

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy HTML
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}

        run: |

          python <<EOF

          import paramiko

          key = paramiko.Ed25519Key.from_private_key_file("key.pem")

          ssh = paramiko.SSHClient()

          ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

          ssh.connect(
              hostname="${HOST}",
              username="${USER}",
              pkey=key
          )

          sftp = ssh.open_sftp()

          sftp.put(
              "templates/index.html",
              "/home/ubuntu/flaskapp/Demo_EC2_Automation/templates/index.html"
          )

          sftp.close()

          ssh.exec_command("sudo systemctl restart flask")

          ssh.close()

          print("Deployment Successful")

          EOF
