name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Paramiko
        run: pip install paramiko

      - name: Deploy HTML to EC2

        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}

        run: |

          cat > deploy.py <<'EOF'

          import paramiko

          ssh = paramiko.SSHClient()
          ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

          private_key = paramiko.RSAKey.from_private_key_file("key.pem")

          ssh.connect(
              hostname="${HOST}",
              username="${USER}",
              pkey=private_key
          )

          sftp = ssh.open_sftp()

          sftp.put(
              "templates/index.html",
              "/home/ubuntu/flaskapp/templates/index.html"
          )

          sftp.close()

          stdin, stdout, stderr = ssh.exec_command(
              "sudo systemctl restart flask"
          )

          print(stdout.read().decode())

          ssh.close()

          EOF

          echo "$KEY" > key.pem

          chmod 600 key.pem

          python deploy.py
